apiVersion: v1
kind: Service
metadata:
    name: "cluster1-6ee6"
    labels:
        app: "cluster1-6ee6"
spec:
    type: LoadBalancer
    ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: http
    selector:
        app: "cluster1-6ee6"